import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
export const DashboardPage = () => {
    const { user, isLoading } = useAuth();
    if (isLoading) {
        return _jsxs("div", { className: "auth-loading", children: [_jsx("div", { className: "spinner" }), _jsx("p", { children: "Loading..." })] });
    }
    return (_jsx("div", { className: "dashboard", children: _jsxs("div", { className: "dashboard-content", children: [_jsxs("div", { className: "dashboard-card", children: [_jsxs("h2", { children: ["Welcome, ", user?.name || user?.email.split('@')[0] || 'User', "! \uD83D\uDC4B"] }), _jsx("p", { className: "description", children: "This is your personalized dashboard. You can navigate to your profile to edit your information." }), _jsx("div", { className: "dashboard-actions", children: _jsx(Link, { to: "/profile", className: "btn btn-primary", children: "View Profile" }) })] }), _jsxs("div", { className: "dashboard-card", children: [_jsx("h3", { children: "Quick Actions" }), _jsxs("div", { className: "action-grid", children: [_jsxs("div", { className: "action-item", children: [_jsx("span", { className: "action-icon", children: "\uD83D\uDCCA" }), _jsx("span", { children: "View Statistics" })] }), _jsxs("div", { className: "action-item", children: [_jsx("span", { className: "action-icon", children: "\u2699\uFE0F" }), _jsx("span", { children: "Settings" })] }), _jsxs("div", { className: "action-item", children: [_jsx("span", { className: "action-icon", children: "\uD83D\uDCE7" }), _jsx("span", { children: "Notifications" })] }), _jsxs("div", { className: "action-item", children: [_jsx("span", { className: "action-icon", children: "\uD83D\uDCB3" }), _jsx("span", { children: "Payment" })] })] })] }), _jsxs("div", { className: "dashboard-card", children: [_jsx("h3", { children: "Account Summary" }), _jsxs("dl", { className: "account-summary", children: [_jsxs("div", { className: "summary-row", children: [_jsx("dt", { children: "User ID" }), _jsx("dd", { children: "12345" })] }), _jsxs("div", { className: "summary-row", children: [_jsx("dt", { children: "Email" }), _jsx("dd", { children: user?.email })] }), _jsxs("div", { className: "summary-row", children: [_jsx("dt", { children: "Role" }), _jsx("dd", { children: "User" })] }), _jsxs("div", { className: "summary-row", children: [_jsx("dt", { children: "Member Since" }), _jsx("dd", { children: new Date().toLocaleDateString() })] })] })] }), _jsxs("div", { className: "dashboard-card", children: [_jsx("h3", { children: "Need Help?" }), _jsx("p", { className: "help-text", children: "If you have any questions or need assistance, please don't hesitate to reach out to our support team." }), _jsx("button", { className: "btn btn-secondary", onClick: () => window.alert('Contact support!'), children: "Contact Support" })] })] }) }));
};
//# sourceMappingURL=DashboardPage.js.map