import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from "../hooks/useAuth";
import { useProfile } from "../hooks/useProfile";
import { AppLayout } from "../AppLayout";
export function ProfilePage() {
    const { user } = useAuth();
    const { name, setName, email, setEmail, isDirty, saveStatus, errorMessage, handleSubmit, handleReset, } = useProfile();
    return (_jsxs(AppLayout, { children: [_jsxs("div", { className: "page-header", children: [_jsx("h2", { children: "Profile" }), _jsx("p", { className: "dashboard-subtitle", children: "Manage your personal information." })] }), _jsxs("div", { className: "profile-page-grid", children: [_jsxs("section", { className: "card", children: [_jsx("h3", { className: "card-title", children: "Account" }), _jsxs("div", { className: "profile-overview", children: [_jsx("div", { className: "avatar avatar-xl", children: user?.avatarInitials }), _jsxs("div", { children: [_jsx("p", { className: "profile-name", children: user?.name }), _jsx("p", { className: "profile-email", children: user?.email }), _jsx("span", { className: "badge", children: "Active" })] })] }), _jsxs("dl", { className: "profile-meta", children: [_jsxs("div", { className: "profile-meta-row", children: [_jsx("dt", { children: "User ID" }), _jsx("dd", { children: _jsx("code", { children: user?.id }) })] }), _jsxs("div", { className: "profile-meta-row", children: [_jsx("dt", { children: "Initials" }), _jsx("dd", { children: user?.avatarInitials })] })] })] }), _jsxs("section", { className: "card", children: [_jsx("h3", { className: "card-title", children: "Edit details" }), _jsxs("form", { onSubmit: handleSubmit, className: "auth-form", noValidate: true, children: [_jsxs("div", { className: "form-group", children: [_jsx("label", { htmlFor: "profile-name", children: "Full name" }), _jsx("input", { id: "profile-name", type: "text", value: name, onChange: (e) => setName(e.target.value), placeholder: "Your full name", autoComplete: "name" })] }), _jsxs("div", { className: "form-group", children: [_jsx("label", { htmlFor: "profile-email", children: "Email address" }), _jsx("input", { id: "profile-email", type: "email", value: email, onChange: (e) => setEmail(e.target.value), placeholder: "you@example.com", autoComplete: "email" })] }), saveStatus === "error" && (_jsx("p", { className: "form-error", role: "alert", children: errorMessage })), saveStatus === "success" && (_jsx("p", { className: "form-success", role: "status", children: "\u2713 Profile updated successfully." })), _jsxs("div", { className: "profile-form-actions", children: [_jsx("button", { type: "button", className: "btn-secondary", onClick: handleReset, disabled: !isDirty && saveStatus === "idle", children: "Reset" }), _jsx("button", { type: "submit", className: "btn-primary", disabled: !isDirty || saveStatus === "saving", children: saveStatus === "saving" ? _jsx("span", { className: "btn-spinner" }) : "Save changes" })] })] })] })] })] }));
}
//# sourceMappingURL=ProfilePage.js.map