import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuthContext } from '../../context';
import { useNavigate } from 'react-router-dom';
import styles from './Dashboard.module.css';
export const DashboardPage = () => {
    const { user, logout } = useAuthContext();
    const navigate = useNavigate();
    const handleLogout = () => {
        logout();
        navigate('/login', { replace: true });
    };
    return (_jsxs("div", { className: styles.container, children: [_jsxs("nav", { className: styles.navbar, children: [_jsx("div", { className: styles.logo, children: "Dashboard" }), _jsxs("div", { className: styles.navLinks, children: [_jsx("button", { onClick: () => navigate('/profile'), className: styles.navLink, children: "Profile" }), _jsx("button", { onClick: handleLogout, className: styles.logoutBtn, children: "Logout" })] })] }), _jsxs("main", { className: styles.main, children: [_jsxs("div", { className: styles.welcome, children: [_jsxs("h1", { children: ["Welcome back, ", user?.name, "!"] }), _jsx("p", { children: "You have successfully logged in to your account." })] }), _jsxs("div", { className: styles.grid, children: [_jsxs("div", { className: styles.card, children: [_jsx("h3", { children: "Profile" }), _jsxs("div", { className: styles.info, children: [_jsxs("p", { children: [_jsx("strong", { children: "Name:" }), " ", user?.name] }), _jsxs("p", { children: [_jsx("strong", { children: "Email:" }), " ", user?.email] }), _jsxs("p", { children: [_jsx("strong", { children: "ID:" }), " ", user?.id] })] }), _jsx("button", { onClick: () => navigate('/profile'), className: styles.editBtn, children: "Edit Profile" })] }), _jsxs("div", { className: styles.card, children: [_jsx("h3", { children: "Statistics" }), _jsxs("div", { className: styles.stats, children: [_jsxs("div", { children: [_jsx("span", { className: styles.statValue, children: "128" }), _jsx("span", { className: styles.statLabel, children: "Tasks" })] }), _jsxs("div", { children: [_jsx("span", { className: styles.statValue, children: "12" }), _jsx("span", { className: styles.statLabel, children: "Projects" })] }), _jsxs("div", { children: [_jsx("span", { className: styles.statValue, children: "5" }), _jsx("span", { className: styles.statLabel, children: "Reports" })] })] })] }), _jsxs("div", { className: styles.card, children: [_jsx("h3", { children: "Activity" }), _jsxs("ul", { className: styles.list, children: [_jsx("li", { children: "Completed task review" }), _jsx("li", { children: "Submitted quarterly report" }), _jsx("li", { children: "Updated project timeline" }), _jsx("li", { children: "Reviewed team assignments" })] })] }), _jsxs("div", { className: styles.card, children: [_jsx("h3", { children: "Quick Actions" }), _jsxs("div", { className: styles.actions, children: [_jsx("button", { className: styles.actionBtn, children: "New Task" }), _jsx("button", { className: styles.actionBtn, children: "Generate Report" }), _jsx("button", { className: styles.actionBtn, children: "View Projects" })] })] })] })] })] }));
};
//# sourceMappingURL=DashboardPage.js.map